########################
##                    ##
##  Default Settings  ##
##                    ##
########################

# use dotbashrc file
set-option -g default-command "/bin/bash"

# Start numbering at 1
set -g base-index 1

# Enable vim binds
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-wi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind-key u copy-mode

# Inherit ENV-Variables into TMUX session
set-option -g update-environment "PATH HOME USER DISPLAY DEFAULT_SESSION SESSIONIZER_PATHS"

# Allows for faster key repetition
set -s escape-time 0

# Colors
set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',xterm-kitty:RGB'

# Mouse control
set -g mouse on

# Renumber windows when windows are closed
set -g renumber-windows on

# Set message timeout
set -g display-time 2000

# Create Space between Tmux Status Bar and Prompt
set-window-option -g pane-border-status bottom
set-window-option -g pane-border-format ''

########################
##                    ##
##       Keymaps      ##
##                    ##
########################

# easy reload config
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "~/.config/tmux/tmux.conf reloaded."

# Change C-b to C-space
unbind C-b
set-option -g prefix C-space
bind-key C-o last-window

# Set window split
bind-key v split-window -h
bind-key b split-window

# hjkl pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Disable confirmation
bind-key x kill-pane

# Disable detach keybind
unbind d

# kill sessions
# kill current session
bind C-c run-shell "tmux neww tmux-cleaner -c"
#kill all sessions
bind C-a run-shell "tmux neww tmux-cleaner -a"

# tmux-sessionizer
bind-key f run-shell "tmux neww tmux-sessionizer"

########################
##                    ##
##      Statusbar     ##
##                    ##
########################

set -g @nord_tmux_show_status_content "0"
set -g status-bg "#2e3440"
set -g status-left "      "
set -g status-right-length 50
set -g status-right "#[fg=blue,bold]#S         "
set -g window-status-format "#[fg=blue]   #W   "
set -g window-status-current-format "#[fg=magenta,bold]   #W   "

########################
##                    ##
##       Plugins      ##
##                    ##
########################

# List of Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'arcticicestudio/nord-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
